openapi: 3.0.1
info:
  title: Gitops Testing 9
  x-cortex-git:
    github:
      alias: maikelorg
      repository: maikelorg/gitops-testing
      basepath: packages/base
  x-cortex-tag: gitops-testing
  x-cortex-type: service
  x-cortex-link:
    - name: OpenAPI Specs
      type: OPENAPI
      url: github:maikelorg/gitops-testing:docs/openapi.json
