openapi: 3.0.1
info:
  title: Gitops Testing 7
  x-cortex-git:
    github:
      alias: Cortex GH
      repository: maikelorg/gitops-testing
  x-cortex-tag: gitops-testing
  x-cortex-type: service
  x-cortex-link:
  - name: OpenAPI Specs
    type: OPENAPI
    url: github:maikelorg/gitops-testing:docs/openapi.json
